In [2]:
import numpy as np
import pandas as pd

#### Q1

In [6]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
a = np.reshape(a,(-1,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q2

In [7]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.where(a%2==0,a,-1)
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q3

In [12]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(f"{np.where(x>y)}, {np.where(x==y)}")

(array([1, 2, 4, 5, 6, 7, 8, 9]),), (array([0]),)


#### Q4

In [18]:
a = np.arange(100).reshape(5,-1)
a[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

#### Q5

In [29]:
np.random.randint(30,41,10)

array([32, 30, 33, 33, 30, 30, 38, 30, 37, 35])

#### Q6

In [40]:
a = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 10)))
b = np.array(((7, 8, 10) ,(4, 5, 6), (1, 2, 3)))
c = a+b
e = a-b
print(c)
print(e)
print(np.sum(a))
print(np.sum(b,1))
print(np.sum(c,0))
dim = c.shape
print(np.reshape(np.sort(np.reshape(c,(-1))),dim))
print(e.T)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]
46
[25 15  6]
[24 30 38]
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]
[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]


In [48]:
import csv
with open("sample.csv", "rt") as f:
    data = csv.reader(f)
    for row in data:
        print(row)
with open("sample.csv", "rt") as f:
    dictData = csv.DictReader(f)
    for raw in dictData:
        print(raw)

['programming language', 'creator', 'year', 'extension']
['java', 'JG', '1995', 'java']
['python', 'GVM', '1991', 'py']
['c++', 'BS', '1983', 'cpp']
OrderedDict([('programming language', 'java'), ('creator', 'JG'), ('year', '1995'), ('extension', 'java')])
OrderedDict([('programming language', 'python'), ('creator', 'GVM'), ('year', '1991'), ('extension', 'py')])
OrderedDict([('programming language', 'c++'), ('creator', 'BS'), ('year', '1983'), ('extension', 'cpp')])


In [56]:
with open('write.csv','w') as f:
    writer = csv.writer(f,delimiter= ',')
    with open("sample.csv", "rt") as ref:
        data = csv.reader(ref)
        for row in data:
            writer.writerow(row)

In [59]:
import pandas as pd
df = pd.read_csv('sample.csv')

In [60]:
df.to_csv('pandasWrite.csv')